spring.application.name=booking-service
server.port=8183

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI_BOOKING:mongodb+srv://localhost/booking-db}

# Service URLs
user-service.url=${USER_SERVICE_URL:http://localhost:8181}
vehicle-service.url=${VEHICLE_SERVICE_URL:http://localhost:8182}
notification-service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8184}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Logging
logging.level.root=INFO
logging.level.com.fastFleet=DEBUG
