spring.application.name=user-service
server.port=8181

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI_USER:mongodb+srv://localhost/user-db}

# JWT Configuration
jwt.secret=${JWT_SECRET:your-secret-key-change-this-in-production-environment-at-least-32-characters-long}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Logging
logging.level.root=INFO
logging.level.com.fastFleet=DEBUG
